{{ if not ( .Values.versuffix ) }}
{{ if .Values.global }}
{{ if .Values.global.configs }}
apiVersion: v1
data:
{{ toYaml $.Values.global.configs | indent 2 }}
kind: ConfigMap
metadata:
  name: global-config
{{- if $.Values.namespace }}
  namespace: {{ $.Values.namespace }}
{{- end }}
{{ end }}
{{ end }}
{{ end }}
