FROM registry.xyb2b.com.cn/base/jdk:1.8.0_101

ENV JAVA_OPTS="-Xmx1024M -Xms1024M -XX:MaxMetaspaceSize=256M -XX:MetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:ErrorFile=./hs_err_pid%p.log -Xloggc:./gc.log -XX:HeapDumpPath=./ -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintClassHistogramBeforeFullGC -XX:+PrintClassHistogramAfterFullGC -XX:+PrintGCApplicationConcurrentTime"

ADD league-guide-application.jar /usr/local/release
#ADD apiclient_cert.p12 /usr/local/release

WORKDIR /usr/local/release

EXPOSE 8542

ENTRYPOINT java ${JAVA_OPTS} -jar league-guide-application.jar \
           --spring.cloud.nacos.config.server-addr=http://nacos.league.xy \
           --spring.cloud.nacos.config.namespace=${PROFILES_ACTIVE} \
           --spring.cloud.nacos.config.group=${CONFIG_GROUP_NAME} \ 
           --spring.cloud.nacos.config.username=nacos \
           --spring.cloud.nacos.config.password=nacos \
           --spring.cloud.nacos.config.fileExtension=yml \
           --spring.cloud.nacos.config.refresh.enabled=true

